package core.entity.key;

public enum ScaleDegree {
  TONIC, // SUPER_TONIC/LEADING_TONE
  SUPER_TONIC, // invalid
  MEDIANT, // POSSIBLY EITHER SUPER_TONIC
  SUB_DOMINANT, // MUST BE SUPER_TONIC
  DOMINANT, // SUPER_TONIC/LEADING_TONE
  SUB_MEDIANT, // LEADING_TONE/SUPER_TONIC
  LEADING_TONE // invalid
}
